export default {
  async fetch(request, env) {
    const response = await env.ASSETS.fetch(request);
    const type = response.headers.get('content-type') || '';
    if (!type.includes('text/html')) return response;

    const html = await response.text();
    const injection = `
<style>
#todayGameRecords{margin-top:18px;padding:16px 0 0;border-top:1px solid rgba(250,246,237,.14)}
#todayGameRecords h3{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#E8C978;margin:0 0 10px}
.today-game{padding:14px 12px;border:1px solid rgba(250,246,237,.10);border-radius:12px;margin:8px 0;background:rgba(250,246,237,.035)}
.today-game:last-child{margin-bottom:0}
.today-game-time{font-size:10px;color:rgba(250,246,237,.5);margin-bottom:9px;text-transform:uppercase;letter-spacing:.08em}
.today-game-teams{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:10px;align-items:center}
.today-team{font-weight:800;line-height:1.35;overflow-wrap:anywhere}
.today-team.right{text-align:right}
.today-score{font-size:21px;font-weight:900;color:#D4A537;white-space:nowrap}
.today-winner{font-size:10px;color:#E8C978;margin-top:8px;font-weight:800}.today-team-avatars{display:flex;gap:4px;margin-bottom:6px}.today-team.right .today-team-avatars{justify-content:flex-end}.today-team-avatars img,.today-team-avatars .blank{width:26px;height:26px;border-radius:50%;object-fit:cover;background:rgba(250,246,237,.12);border:1px solid rgba(212,165,55,.4);display:inline-block}
@media(max-width:430px){.today-game-teams{gap:7px}.today-score{font-size:18px}.today-game{padding:12px 10px}}</style>
<script>
/* LB_GAME_RECORDS_TOP_V1 */
(function(){
'use strict';
const U='https://zcahhfswtdrdmguppqtp.supabase.co';
const K='sb_publishable_CeiB5DOuyX7xKdK87tK2QQ_5Y9phmOs';
const A='a517d9bd-bc9c-4e59-b36d-503747621aa4';
const db=window.supabase.createClient(U,K);
const $=id=>document.getElementById(id);
const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};const dn=p=>{if(!p)return '';const fn=(p.full_name||p.name||'Player').trim();const parts=fn.split(/\\s+/);return parts.length>1?parts[0]+' '+parts[1][0]+'.':parts[0];};const localDate=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
let installed=false,historyInstalled=false,gameRecordsLast=0,weekIdsCache=[],historyDataCache=null;
function close(){const x=$('lbAdminModal');if(x)x.remove()}
function modal(html){let x=$('lbAdminModal');if(!x){x=document.createElement('div');x.id='lbAdminModal';x.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.78);z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px';document.body.appendChild(x)}x.innerHTML='<div style="width:100%;max-width:560px;max-height:90vh;overflow:auto;background:#163A30;border:1px solid rgba(250,246,237,.16);border-radius:14px;padding:20px;color:#FAF6ED">'+html+'</div>';return x}
async function admin(){const r=await db.auth.getSession();return r.data?.session?.user?.id===A}
function removePins(){const b=$('modalBox');if(!b)return;[...b.querySelectorAll('input,select,textarea,label')].filter(x=>/pin/i.test((x.id||'')+' '+(x.name||'')+' '+(x.placeholder||'')+' '+(x.textContent||''))).forEach(x=>x.remove())}
async function photo(){if(!await admin())return alert('Admin login required.');const r=await db.from('players').select('id,name,nickname').order('name');if(r.error)return alert(r.error.message);const opts=(r.data||[]).map(p=>'<option value="'+esc(p.id)+'">'+esc(dn(p))+'</option>').join('');modal('<h2 style="margin-top:0">Add / Change Profile Photo</h2><div class="muted">Admin only · images up to 5 MB.</div><select id="apPlayer" class="field" style="width:100%;margin:10px 0">'+opts+'</select><input id="apFile" class="field" type="file" accept="image/*" style="width:100%"><div style="margin-top:14px"><button id="apSave" class="btn gold">Upload Photo</button><button id="apClose" class="btn ghost" style="margin-left:6px">Cancel</button></div>');$('apClose').onclick=close;$('apSave').onclick=async()=>{const f=$('apFile').files?.[0],id=$('apPlayer').value;if(!f)return alert('Choose a player and photo.');if(!f.type.startsWith('image/'))return alert('Please choose an image.');if(f.size>5*1024*1024)return alert('Photo must be under 5 MB.');const b=$('apSave');b.disabled=true;b.textContent='Uploading…';const ext=(f.type.split('/')[1]||'jpg').replace(/[^a-z0-9]/gi,'')||'jpg';const path=id+'/'+Date.now()+'.'+ext;const up=await db.storage.from('profile-avatars').upload(path,f,{upsert:true,contentType:f.type});if(up.error){b.disabled=false;b.textContent='Upload Photo';return alert('Could not upload photo: '+up.error.message)}const url=db.storage.from('profile-avatars').getPublicUrl(path).data.publicUrl;const q=await db.from('players').update({avatar_url:url}).eq('id',id);if(q.error){b.disabled=false;b.textContent='Upload Photo';return alert('Could not save photo: '+q.error.message)}close();location.reload()}}
async function deleteGame(){if(!await admin())return alert('Admin login required.');const r=await db.from('games').select('id,played_at,winner_score,loser_score').order('played_at',{ascending:false});if(r.error)return alert(r.error.message);const opts=(r.data||[]).map(g=>'<option value="'+esc(g.id)+'">'+esc(g.played_at?new Date(g.played_at).toLocaleString():'Game')+' · '+esc((g.winner_score??'—')+'–'+(g.loser_score??'—'))+'</option>').join('');modal('<h2 style="margin-top:0">Delete Accidental Game</h2><select id="agGame" class="field" style="width:100%;margin:10px 0">'+opts+'</select><button id="agDelete" class="btn danger">Delete Game</button><button id="agClose" class="btn ghost" style="margin-left:6px">Cancel</button>');$('agClose').onclick=close;$('agDelete').onclick=async()=>{const id=$('agGame').value;if(!id||!confirm('Delete this game permanently?'))return;const b=$('agDelete');b.disabled=true;b.textContent='Deleting…';const q=await db.from('games').delete().eq('id',id);if(q.error){b.disabled=false;b.textContent='Delete Game';return alert('Could not delete game: '+q.error.message)}close();location.reload()}}
async function deleteProfile(){if(!await admin())return alert('Admin login required.');const r=await db.from('players').select('id,name,nickname').order('name');if(r.error)return alert(r.error.message);const opts=(r.data||[]).map(p=>'<option value="'+esc(p.id)+'">'+esc(dn(p))+'</option>').join('');modal('<h2 style="margin-top:0">Delete Profile</h2><select id="adPlayer" class="field" style="width:100%;margin:10px 0">'+opts+'</select><button id="adDelete" class="btn danger">Delete Profile</button><button id="adClose" class="btn ghost" style="margin-left:6px">Cancel</button>');$('adClose').onclick=close;$('adDelete').onclick=async()=>{const id=$('adPlayer').value,label=$('adPlayer').selectedOptions[0]?.textContent||'this player';if(!id||!confirm('Delete '+label+' permanently?'))return;const b=$('adDelete');b.disabled=true;b.textContent='Deleting…';const q=await db.rpc('admin_delete_player',{p_player_id:id});if(q.error){b.disabled=false;b.textContent='Delete Profile';return alert('Could not delete profile: '+q.error.message)}close();location.reload()}}
async function pastPoints(){if(!await admin())return alert('Admin login required.');const p=await db.from('players').select('id,name,nickname,full_name,active').order('name');if(p.error)return alert('Could not load players: '+p.error.message);modal('<h2 style="margin-top:0">Add / Edit Past Points</h2><div class="muted">Choose a date. Existing points for that date load automatically. Enter 0 for a player with no points.</div><div class="row" style="margin-top:10px"><input id="ppDate" type="date" class="field"><button id="ppLoad" class="btn ghost">Load</button></div><div id="ppRows" style="margin-top:12px"></div><div id="ppStatus" class="muted" style="margin-top:8px"></div><div style="margin-top:14px"><button id="ppSave" class="btn gold" disabled>Save Past Points</button><button id="ppClose" class="btn ghost" style="margin-left:6px">Cancel</button></div>');const date=$('ppDate'),rows=$('ppRows'),status=$('ppStatus'),save=$('ppSave');$('ppClose').onclick=close;const load=async()=>{const d=date.value;if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(d))return status.textContent='Choose a valid date.';status.textContent='Loading…';const old=await db.from('past_points').select('player_id,points').eq('session_date',d);if(old.error)return status.textContent='Could not load points: '+old.error.message;const by=new Map((old.data||[]).map(x=>[x.player_id,Number(x.points)||0]));rows.innerHTML='';(p.data||[]).filter(x=>x.active!==false).forEach(x=>{const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:1fr 95px;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid rgba(250,246,237,.14)';row.innerHTML='<div><strong>'+esc(dn(x))+'</strong><div class="muted">'+esc(x.full_name||x.name||'')+'</div></div>';const i=document.createElement('input');i.type='number';i.min='0';i.max='99';i.step='1';i.className='field';i.dataset.player=x.id;i.value=String(by.get(x.id)||0);row.appendChild(i);rows.appendChild(row)});save.disabled=false;status.textContent=old.data?.length?'Existing points loaded — edit and save.':'No points for this date yet.'};$('ppLoad').onclick=load;date.onchange=load;save.onclick=async()=>{const d=date.value;if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(d))return status.textContent='Choose a valid date.';const vals=[...rows.querySelectorAll('input[data-player]')].map(i=>({player_id:i.dataset.player,points:Math.max(0,Math.min(99,Number(i.value)||0))}));save.disabled=true;save.textContent='Saving…';const q=await db.rpc('admin_set_past_points',{p_session_date:d,p_entries:vals});if(q.error){save.disabled=false;save.textContent='Save Past Points';return status.textContent='Could not save past points: '+q.error.message}status.textContent='Saved successfully ✓';save.textContent='Saved ✓';setTimeout(()=>{close();location.reload()},600)};date.value=localDate(new Date());await load()}
function weekId(d){const x=new Date(d+'T00:00:00');x.setHours(0,0,0,0);const n=x.getDay();x.setDate(x.getDate()+(n===0?-6:1-n));return localDate(x)}
function weekText(id){const s=new Date(id+'T00:00:00');s.setDate(s.getDate()+3);return s.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function gamePoints(g){const w=Number(g.winner_score),l=Number(g.loser_score);if(!Number.isFinite(w)||!Number.isFinite(l))return{w:0,l:0};const scale=Math.min(w,21)/21;return{w:Math.round(3*scale*2)/2,l:w-l<=3?Math.round(1*scale*2)/2:0}}
function fmtPts(n){return (Math.round(n*10)/10).toString().replace(/\\.0$/,'')}
function ids(v){if(Array.isArray(v))return v;try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch(e){return typeof v==='string'?v.split(',').map(x=>x.trim()).filter(Boolean):[]}}
function findPlayer(ps,v){return ps.find(p=>p.id===v||p.name===v||p.nickname===v||(dn(p))===v)}
async function historyData(){const [pr,gr,pp]=await Promise.all([db.from('players').select('id,name,nickname,full_name,avatar_url,active').order('name'),db.from('games').select('*').order('played_at',{ascending:true}),db.from('past_points').select('*')]);if(pr.error||gr.error)return null;if(pp.error)console.warn('past_points unavailable (this role likely lacks SELECT grant on it):',pp.error.message);return{players:pr.data||[],games:gr.data||[],past:pp.error?[]:(pp.data||[])}}
function historyStats(id,data){const by={};data.players.forEach(p=>by[p.id]={p,wins:0,games:0,points:0});data.games.filter(g=>(g.week_id||weekId(localDate(new Date(g.played_at||Date.now()))))===id).forEach(g=>{const q=gamePoints(g);ids(g.winners).concat(ids(g.losers)).forEach(v=>{const p=findPlayer(data.players,v);if(p)by[p.id].games++});ids(g.winners).forEach(v=>{const p=findPlayer(data.players,v);if(p){by[p.id].wins++;by[p.id].points+=q.w}});ids(g.losers).forEach(v=>{const p=findPlayer(data.players,v);if(p)by[p.id].points+=q.l})});data.past.filter(x=>weekId(x.session_date)===id).forEach(x=>{if(by[x.player_id])by[x.player_id].points+=Number(x.points)||0});return Object.values(by).filter(x=>x.games||x.points).map(x=>({...x,winPct:x.games?x.wins/x.games:0,score:(x.wins+3)/(x.games+6)})).sort((a,b)=>(b.score-a.score)||(b.points-a.points)||(b.games-a.games)||a.p.name.localeCompare(b.p.name))}
async function historyView(){if(historyInstalled)return;const h=$('history');if(!h)return;const data=await historyData();if(!data)return;const current=weekId(localDate(new Date()));const idsList=[...new Set(data.games.map(g=>g.week_id||weekId(localDate(new Date(g.played_at||Date.now())))).concat(data.past.map(x=>weekId(x.session_date))))].sort().reverse().filter(x=>x!==current);weekIdsCache=idsList;historyDataCache=data;h.innerHTML='';const empty=$('historyEmpty');if(empty)empty.classList.toggle('hidden',idsList.length>0);idsList.forEach(id=>{const s=historyStats(id,data),top=s.slice(0,3),box=document.createElement('div');box.className='week';box.innerHTML='<button type="button" class="btn ghost" style="width:100%;text-align:left" data-week="'+esc(id)+'"><strong>📅 '+esc(weekText(id))+'</strong><div class="muted" style="margin-top:6px">'+(top.length?top.map((x,i)=>['🥇','🥈','🥉'][i]+' '+esc(dn(x.p))+' · '+Math.round(x.winPct*100)+'% win').join(' &nbsp; '):'No results')+'</div><div class="muted" style="margin-top:6px">Tap to view full leaderboard →</div></button>';h.appendChild(box);box.querySelector('[data-week]').onclick=()=>showHistory(id,data)})
historyInstalled=true}
function bindSwipe(el,onLeft,onRight){if(!el)return;let x0=null,y0=null;el.ontouchstart=e=>{const t=e.touches[0];x0=t.clientX;y0=t.clientY};el.ontouchend=e=>{if(x0===null)return;const t=e.changedTouches[0];const dx=t.clientX-x0,dy=t.clientY-y0;x0=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5){if(dx<0)onLeft();else onRight()}}}
async function showHistory(id,data){if(data)historyDataCache=data;else data=historyDataCache;if(!data)return;const isAdmin=await admin();const s=historyStats(id,data),top=s.slice(0,3),pod=top.map((x,i)=>'<div class="pod '+['one','two','three'][i]+'">'+(x.p.avatar_url?'<img src="'+esc(x.p.avatar_url)+'">':'<span class="blank"></span>')+'<div class="podName">'+esc(dn(x.p))+'</div><div class="podPoints">'+Math.round(x.winPct*100)+'% win · '+fmtPts(x.points)+' pts</div><div class="podBase">'+['🥇','🥈','🥉'][i]+'</div></div>').join(''),rows=s.map((x,i)=>'<div class="lb"><div class="rank">'+(i+1)+'</div><div>'+(x.p.avatar_url?'<div class="avatar"><img src="'+esc(x.p.avatar_url)+'"></div>':'<div class="avatar"></div>')+'</div><div class="name">'+esc(dn(x.p))+'<div class="full">'+esc(x.p.full_name||x.p.name||'')+'</div></div><div class="stats"><div class="pts">'+Math.round(x.winPct*100)+'% win</div><div class="wl">'+x.wins+'W · '+x.games+' games · '+fmtPts(x.points)+' pts</div></div></div>').join('');const idx=weekIdsCache.indexOf(id);const hasOlder=idx!==-1&&idx<weekIdsCache.length-1;const hasNewer=idx>0;const nav=idx!==-1?'<div class="row" style="justify-content:space-between;margin-top:14px"><button id="histPrev" class="btn ghost" '+(hasOlder?'':'disabled')+'>← Older</button><div class="muted" style="align-self:center">Swipe to browse weeks</div><button id="histNext" class="btn ghost" '+(hasNewer?'':'disabled')+'>Newer →</button></div>':'';modal('<div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">🏆 Weekly History</h2><div class="muted" style="margin-top:4px">'+esc(weekText(id))+'</div></div><button id="histClose" class="btn ghost">Close</button></div><div class="podium">'+(pod||'<div class="muted">No results for this week.</div>')+'</div><h2 style="margin-top:18px">Leaderboard</h2><div>'+rows+'</div>'+nav+(isAdmin?'<div class="row" style="margin-top:16px"><button id="histEdit" class="btn gold">✏️ Edit Week</button><button id="histDelete" class="btn danger">🗑️ Delete Week</button></div>':'') );$('histClose').onclick=close;if($('histEdit'))$('histEdit').onclick=()=>{close();pastPoints()};if($('histDelete'))$('histDelete').onclick=()=>deleteHistory(id,data);if($('histPrev'))$('histPrev').onclick=()=>{if(hasOlder)showHistory(weekIdsCache[idx+1])};if($('histNext'))$('histNext').onclick=()=>{if(hasNewer)showHistory(weekIdsCache[idx-1])};if(idx!==-1)bindSwipe($('lbAdminModal').firstElementChild,()=>{if(hasNewer)showHistory(weekIdsCache[idx-1])},()=>{if(hasOlder)showHistory(weekIdsCache[idx+1])})}
async function deleteHistory(id,data){if(!await admin())return alert('Admin login required.');if(!confirm('Delete this entire weekly history? This will remove its recorded games and past points.'))return;const g=await db.from('games').delete().eq('week_id',id);if(g.error)return alert('Could not delete games: '+g.error.message);const dates=[...new Set(data.past.filter(x=>weekId(x.session_date)===id).map(x=>x.session_date))];for(const d of dates){const q=await db.from('past_points').delete().eq('session_date',d);if(q.error)return alert('Could not delete past points: '+q.error.message)}historyInstalled=false;close();location.reload()}
async function gameRecords(){if(Date.now()-gameRecordsLast<5000)return;gameRecordsLast=Date.now();const host=$('podium');if(!host)return;let box=$('todayGameRecords');if(!box){box=document.createElement('div');box.id='todayGameRecords';host.insertAdjacentElement('beforebegin',box)}const [gr,pr]=await Promise.all([db.from('games').select('id,played_at,winners,losers,winner_score,loser_score').order('played_at',{ascending:false}),db.from('players').select('id,name,nickname,full_name,avatar_url').order('name')]);if(gr.error||pr.error){box.innerHTML='';return}const ps=pr.data||[],today=new Date();const games=(gr.data||[]).filter(g=>{const d=new Date(g.played_at||0);return d.toDateString()===today.toDateString()});let html='<h3 style="font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#E8C978;margin:0 0 8px">📋 Game Records</h3>';if(!games.length){html+='<div class="muted">No games recorded today yet.</div>'}else{const av=p=>p&&p.avatar_url?'<img src="'+esc(p.avatar_url)+'">':'<span class="blank"></span>';html+=games.map((g,i)=>{const winnerPs=ids(g.winners).map(v=>findPlayer(ps,v));const loserPs=ids(g.losers).map(v=>findPlayer(ps,v));const winners=winnerPs.map(p=>dn(p)||'Player');const losers=loserPs.map(p=>dn(p)||'Player');const wt=winners.length?winners.join(' + '):'Winning team';const lt=losers.length?losers.join(' + '):'Losing team';const ws=g.winner_score??'—',ls=g.loser_score??'—';const time=g.played_at?new Date(g.played_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'';const wAv='<div class="today-team-avatars">'+winnerPs.map(av).join('')+'</div>';const lAv='<div class="today-team-avatars">'+loserPs.map(av).join('')+'</div>';return '<div class="today-game"><div class="today-game-time">Game '+(games.length-i)+' · '+esc(time)+'</div><div class="today-game-teams"><div class="today-team">'+wAv+esc(wt)+'</div><div class="today-score">'+esc(ws)+' – '+esc(ls)+'</div><div class="today-team right">'+esc(lt)+lAv+'</div></div><div class="today-winner">🏆 '+esc(wt)+' won</div></div>'}).join('')}box.innerHTML=html}
async function addPlayerTool(){if(!await admin())return alert('Admin login required.');modal('<h2 style="margin-top:0">Add Player</h2><div class="muted">Players are shown as first name + last initial (e.g. "Amna S.").</div><input id="npFirst" class="field" placeholder="First name" maxlength="30" style="width:100%;margin:10px 0 8px"><input id="npLast" class="field" placeholder="Last name" maxlength="30" style="width:100%"><div id="npStatus" class="muted" style="margin-top:8px"></div><div style="margin-top:14px"><button id="npSave" class="btn gold">Add Player</button><button id="npClose" class="btn ghost" style="margin-left:6px">Cancel</button></div>');const first=$('npFirst'),last=$('npLast'),status=$('npStatus'),save=$('npSave');$('npClose').onclick=close;const submit=async()=>{const f=first.value.trim(),l=last.value.trim();if(!f)return status.textContent='Enter a first name.';const full=l?f+' '+l:f;const r=await db.from('players').select('id,name,full_name');if(r.error)return status.textContent='Could not check existing players: '+r.error.message;if((r.data||[]).some(p=>(p.full_name||p.name||'').toLowerCase()===full.toLowerCase()))return status.textContent='That name is already taken.';save.disabled=true;save.textContent='Saving…';const q=await db.from('players').insert({name:f,full_name:full,date_joined:localDate(new Date()),active:true});if(q.error){save.disabled=false;save.textContent='Add Player';return status.textContent=q.error.code==='23505'?'That name is already taken.':'Could not add player: '+q.error.message}close();location.reload()};save.onclick=submit;last.onkeydown=e=>{if(e.key==='Enter')submit()}}
async function archiveProfile(){if(!await admin())return alert('Admin login required.');const r=await db.from('players').select('id,name,nickname,full_name,active').order('name');if(r.error)return alert(r.error.message);const ps=r.data||[];const opts=ps.map(p=>'<option value="'+esc(p.id)+'">'+esc(dn(p))+(p.active===false?' (archived)':'')+'</option>').join('');modal('<h2 style="margin-top:0">Archive / Unarchive Profile</h2><div class="muted">Archiving hides a player from the roster and Standings while keeping their stats and history. It does not delete anything.</div><select id="arPlayer" class="field" style="width:100%;margin:10px 0">'+opts+'</select><div id="arStatus" class="muted" style="margin-bottom:10px"></div><button id="arToggle" class="btn gold">Archive Player</button><button id="arClose" class="btn ghost" style="margin-left:6px">Cancel</button>');const sel=$('arPlayer'),status=$('arStatus'),btn=$('arToggle');const sync=()=>{const p=ps.find(x=>x.id===sel.value);const archived=p&&p.active===false;status.textContent=archived?'Currently archived.':'Currently active.';btn.textContent=archived?'Unarchive Player':'Archive Player'};sel.onchange=sync;sync();$('arClose').onclick=close;btn.onclick=async()=>{const p=ps.find(x=>x.id===sel.value);if(!p)return;const nextActive=p.active===false;btn.disabled=true;btn.textContent='Saving…';const q=await db.from('players').update({active:nextActive}).eq('id',p.id);if(q.error){btn.disabled=false;sync();return alert('Could not update profile: '+q.error.message)}close();location.reload()}}
function install(){const adminBox=$('adminPanel');if(!adminBox||adminBox.classList.contains('hidden')){installed=false;return}if(installed)return;const box=document.createElement('div');box.id='lbAdminTools';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid rgba(250,246,237,.14)';box.innerHTML='<div style="font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#E8C978;margin-bottom:9px">Admin Tools</div><div class="row"><button id="lbAddPlayer" class="btn gold" type="button">➕ Add Player</button><button id="lbPhoto" class="btn gold" type="button">Add / Change Profile Photo</button><button id="lbArchive" class="btn ghost" type="button">📦 Archive / Unarchive Profile</button><button id="lbGameDelete" class="btn danger" type="button">Delete Accidental Game</button><button id="lbProfileDelete" class="btn danger" type="button">Delete Profile</button><button id="lbPast" class="btn ghost" type="button">Add / Edit Past Points</button></div>';adminBox.appendChild(box);$('lbAddPlayer').onclick=addPlayerTool;$('lbPhoto').onclick=photo;$('lbArchive').onclick=archiveProfile;$('lbGameDelete').onclick=deleteGame;$('lbProfileDelete').onclick=deleteProfile;$('lbPast').onclick=pastPoints;const old=$('pastGame');if(old){old.onclick=pastPoints;old.dataset.ppBound='1'}installed=true}
function loop(){removePins();install();const old=$('pastGame');if(old&&old.dataset.ppBound!=='1'){old.onclick=pastPoints;old.dataset.ppBound='1'}if($('history')&&!historyInstalled)historyView();gameRecords()}
setInterval(loop,800);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loop);else loop();
})();
</script>`;
    const body = html.includes('</body>') ? html.replace('</body>', injection + '</body>') : html + injection;
    return new Response(body, { status: response.status, statusText: response.statusText, headers: response.headers });
  }
};
